version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/balj/src/collegedisha
      - /balj/src/collegedisha/node_modules
      - /balj/src/collegedisha/.next