version: "3.3"

services:
  nextjs:
    ports:
      - "3000:3000"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/balj/src/collegedisha
      - /balj/src/collegedisha/node_modules
      - /balj/src/collegedisha/.next



# version: "3.7"

# x-common-props: &common-props
#   build:
#     context: ./
#     target: base
#   working_dir: /base
#   volumes:
#     - ./app:/base
#     - node_modules:/base/node_modules

# services:
#   npm:
#     <<: *common-props
#     entrypoint: npm
#   dev:
#     <<: *common-props
#     ports:
#       - "3000:3000"
#     command: npm run dev
# volumes:
#   node_modules: