const Routes = {
    Home: '/',
    Login: '/login',
    User: '/user',
    About: '/about',
    Contact: '/contact',
    Register: '/register',
    PrivacyPolicy: '/privacy-policy',
    TermsConditions: '/website-usage-policy',
    EmailVerification: 'changeloginpassword',
    FAQ: '/faq',
    Founder: '/college-disha-founder',
    Disclaimer: '/disclaimer',
    Advertisement: '/write-for-us',
    Institutes: '/institutes',
    Colleges: '/colleges',
    Coachings: '/coaching',
    CareerOptions: '/career-options',
    Exams: '/exams',
    ExamCategory: '/category',
    Boards: '/education-boards',
    Articles: '/articles',
    Courses: '/courses',
    News: '/news',
    Universities: '/universities',
    ProfileEdit: '/profile-edit/',
    Profile: '/profile/',
    MailSent: '/mailSent',
    Emailverification: '/email-verication',
    OtpVerification: '/otpVerication',
    Verification: '/verification',
    Mobileverification: '/mobileverification',
    PasswordChange: '/change-password',
    ResetPassword: '/reset-password',
}

export default Routes;